
export const ACTIVITY_TYPES = {
    EXPENSE_CREATE: "EXPENSE_CREATE",
    EXPENSE_UPDATE: "EXPENSE_UPDATE",
    EXPENSE_DELETE: "EXPENSE_DELETE",
    SETTLEMENT_ADD: "SETTLEMENT_ADD",
    GROUP_JOIN: "GROUP_JOIN",
    GROUP_LEAVE: "GROUP_LEAVE",
} as const;

export type ActivityType = keyof typeof ACTIVITY_TYPES;