
export const ACTIVITY_TYPES = {
    EXPENSE_CREATE: "EXPENSE_CREATE",
    EXPENSE_UPDATE: "EXPENSE_UPDATE",
    EXPENSE_DELETE: "EXPENSE_DELETE",
    SETTLEMENT_CREATE: "SETTLEMENT_CREATE",
    GROUP_JOIN: "GROUP_JOIN",
    GROUP_LEAVE: "GROUP_LEAVE",
    SIMPLIFY_DEBTS: "SIMPLIFY_DEBTS",
    GROUP_CREATE: "GROUP_CREATE",
} as const;

export type ActivityType = keyof typeof ACTIVITY_TYPES;